on:
  workflow_call:
  push:


concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-test2-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test2-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test 2"
