on:
  workflow_call:
  push:


concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test3-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test 3"
